### PR TITLE
cli: basic validation of config flags and config file, fixes #548

### LINKED ISSUE #548: Colima should validate vm-type and mount-type flags
### Description

I was working on a recreation scenario for #503 and tried a number of things.

`colima start junk --vm-type=qemu --mount-type=""` was accepted, but shouldn't a valid mountType be required?

It results in `mountType: ""` and

```
$ colima status -p junk
INFO[0000] colima [profile=junk] is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] socket: unix:///Users/rfay/.colima/junk/docker.sock
```

(Note that the mountType is not reported there)

But the mountType ends up being 9p, so 9p seems to be the default still on 0.5.2?

But... Unable to recreate the problem described here using this technique.

I was even able to do 
* `colima start j2 --mount-type="xxx" --vm-type=qemu` with no complaint from colima
* and  `colima start j3 --mount-type="xxx" --vm-type=xxx` 

I recommend validation on each of those arguments (and all of the rest as well). 

I note that manually changing colima.yaml with `mountType: yyy` and `vmType: yyy` also results in no validation on start. 

`colima status -p j3` shows
```
$ colima status -p j3
INFO[0000] colima [profile=j3] is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: yyy
INFO[0000] socket: unix:///Users/rfay/.colima/j3/docker.sock
```

Apparently it decides QEMU is the thing to do, but it thinks that mountType is `yyy`. 

### Version

Colima Version: 0.5.2
Lima Version: 0.14.2
Qemu Version: 7.2.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```
$ colima status -p j3
INFO[0000] colima [profile=j3] is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: yyy
INFO[0000] socket: unix:///Users/rfay/.colima/j3/docker.sock
```

### Reproduction Steps

described above

### Expected behaviour

Failure for unsupported vm type or mount type

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rfay**
This is a start at config validation for
* #548

It's as far as I'll get right now, but it's a start. I'd rather add tests and such, but think I'll be lost on it for too long.

**Note that this does not allow empty values in config for vm-type, network-driver, mount-type, and those were previously allowed, but seemed to have unusual results in many cases.**

```
$ _output/binaries/colima-Darwin-arm64 start -p c --vm-type=xxx
FATA[0000] invalid vmType: 'xxx'

$ _output/binaries/colima-Darwin-arm64 start -p c --mount-type=xxx
WARN[0000] config load failed: invalid vmType: 'xxx'
WARN[0000] reverting to default settings
FATA[0000] invalid mountType: 'xxx'

# With mountType set to yyy in config file:
$ _output/binaries/colima-Darwin-arm64 start -p c
WARN[0000] config load failed: invalid mountType: 'yyy'
WARN[0000] reverting to default settings
FATA[0000] invalid mountType: 'yyy'
```

I'm sure you have preferences of other ways to do a bit of this, and I'm fine with going a different direction.

Edit: This adds [tmate action](https://github.com/mxschmitt/action-tmate) to the integration tests, which allows you to ssh  into a test and manually interact with it. You can't use it until it goes into main branch, after that you would start it with the actions menu, https://github.com/abiosoft/colima/actions/workflows/integration.yml - and use the "Run Workflow" button:

Actions_·_rfay_colima

### CODE REVIEW

**Comment by rfay** [comment]
Integration tests all fail like
```
colima start --runtime docker
  shell: /bin/bash -e {0}
time="2022-12-[3](https://github.com/abiosoft/colima/actions/runs/3809687340/jobs/6481210383#step:6:3)1T00:02:5[4](https://github.com/abiosoft/colima/actions/runs/3809687340/jobs/6481210383#step:6:5)Z" level=fatal msg="invalid vmType: ''"
```

but that command works fine for me.... Is there an injected template or colima.yaml here or something with empty vmType? I don't see it...

**Comment by abiosoft** [comment]
> Integration tests all fail like
> 
> ```
> colima start --runtime docker
>   shell: /bin/bash -e {0}
> time="2022-12-[3](https://github.com/abiosoft/colima/actions/runs/3809687340/jobs/6481210383#step:6:3)1T00:02:5[4](https://github.com/abiosoft/colima/actions/runs/3809687340/jobs/6481210383#step:6:5)Z" level=fatal msg="invalid vmType: ''"
> ```
> 
> but that command works fine for me.... Is there an injected template or colima.yaml here or something with empty vmType? I don't see it...

That is mainly due to GitHub not having support for macOS 13 yet.

File: config/configmanager/config.go [hunk 1]
```diff
@@ -50,9 +50,36 @@ func LoadFrom(file string) (config.Config, error) {
...
+		return fmt.Errorf("invalid networkDriver: '%s'", c.Network.Driver)
+	}
+
+	validMountTypes := map[string]bool{"9p": true, "sshfs": true, "virtiofs": true}
+	if _, ok := validMountTypes[c.MountType]; !ok {
+		return fmt.Errorf("invalid mountType: '%s'", c.MountType)
+	}
+	validVMTypes := map[string]bool{"qemu": true, "vz": true}
+	if _, ok := validVMTypes[c.VMType]; !ok {
+		return fmt.Errorf("invalid vmType: '%s'", c.VMType)
```
Comment (abiosoft) [inline config/configmanager/config.go:77]: To fix the integration tests error, this should be under the condition of `if util.MacOS13orNewer`

**Comment by rfay** [comment]
I don't seem to have a machine or test runner anywhere now that is still on Monterrey, so will try to use tmate to debug on macOS 12, but unfortunately Github is on a rampage about rate limiting api requests in the last couple of weeks, so tmate isn't working.

File: cmd/start.go [hunk 2]
```diff
@@ -217,6 +221,7 @@ func mountsFromFlag(mounts []string) []config.Mount {
 }
 
 func setDefaults(cmd *cobra.Command) {
+	startCmdArgs.VMType = "qemu"
```
Comment (rfay) [inline cmd/start.go:224]: This was the key to getting it to work on macOS 12. But as mentioned elsewhere, we may have trouble with existing configuration files that have the assumption of default values being a particular thing, as the validation insists on an actual value.

File: config/configmanager/config.go (hunk 1 above)
Comment (rfay) [reply config/configmanager/config.go:84]: Done, thanks

**Review by abiosoft — APPROVED** [review]
